@isTest
public with sharing class AutoTraderSelectionModelErrorTest {
    /*
    @isTest
    public static void errorTest1(){
        test.startTest();
        List<MediationRequest__c> mediationRequests = new List<MediationRequest__c>();
        MediationRequest__c mediationRequest = new MediationRequest__c(
            RequestTraderId__c = 'test000000BYu7xMAD',
            NewMatterId__c = 'test000000BYu7xMAD'
        );
        mediationRequests.add(mediationRequest);
        AutoTraderSelectionModel.insertMediationRequest(mediationRequests);
        test.stopTest();
    }
    @isTest
    public static void errorTest2(){
        test.startTest();
        List<Task> tasks = new List<Task>();
        Task task = new Task(
            whatId = 'test000000BYu7xMAD'        );
        tasks.add(task);
        AutoTraderSelectionModel.insertTask(tasks);
        test.stopTest();
    }
    */
}