@istest
public with sharing class AutoTraderSelectionHandlerTest {
    @isTest    
    public static void AutoTraderSelectionHandlerTest() {
        /*
        system.debug('AutoTraderSelectionHandlerTest BeforeQuerisLimits :'+limits.getQueries());


       //カスタム設定
       TraderSelectionTestDataFactory.createSyatakusanSetting();
       TraderSelectionTestDataFactory.createTraderSelectionSetting();

        //取引先(不動産会社)作成
        TraderSelectionTestDataFactory.createAccount_MC_TraderSelection();

        //申請レコード作成
        List<Application__c> applications = TraderSelectionTestDataFactory.createApplication_TraderSelection();

        //新規レコード
        test.startTest();
        TraderSelectionTestDataFactory.createNewMatter_one_TraderSelection(applications);
        test.stopTest();
        */
    }
}