/**
 * @Description: Testing for class PhaseGate.
 * 
 * @author t-ooshiro-bp
 * @date 2022/07/26
 */
@isTest
private class PhaseGateTriggerTest {
    /*
    @isTest static void newMatterTest(){
        //カスタム設定を作成
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        //SyatakusanSetting__c customSetting = createCustomSetting();

        Test.startTest();
        try{
            List<NewMatter__c> newMatterList = PhaseGateCreateNewMatterTestData.createData();//新規テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void cancelTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Cancel__c> cancelList = PhaseGateCreateCancelTestData.createData();//解約テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void renewalTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Renewal__c> renewalList = PhaseGateCreateRenewalTestData.createData();//更新テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }
    @isTest static void conditionChangeTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<ConditionChange__c> conditionChangeList = PhaseGateCreateConditionChangeTestData.createData();//条件変更テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void changeTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Change__c> changeList = PhaseGateCreateChangeTestData.createData();//入替テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void caseTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<Case> caseList = PhaseGateCreateCaseTestData.createData();//ケーステストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }

    @isTest static void cancelCalculateTest(){
        // カスタム設定を作成
        TraderSelectionTestDataFactory.createTraderSelectionSetting();
        TraderSelectionTestDataFactory.createSyatakusanSetting();
        Test.startTest();
        try{
            List<CancelCalculate__c> cancelCalculateList = PhaseGateCreateCancelCalculateTestData.createData();//解約精算テストデータ
        }catch(DmlException e){
            System.debug(e);
        }
        Test.stopTest();
    }
    */
}